version: "3.8"
services:
  postgresql:
    image: postgres:16
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: clgportal
      POSTGRES_USER: ajay
      POSTGRES_PASSWORD: O5c9TYPE7gkvZXdgOvbfSaByJbCmfXmV
    networks:
      - clgportal-network  

  spring-boot-app:
       build:
          context: .
       environment:
         SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cupe9hogph6c73duobd0-a.oregon-postgres.render.com/clgportal  # Connecting to the 'postgresql' service
         SPRING_DATASOURCE_USERNAME: ajay
         SPRING_DATASOURCE_PASSWORD: O5c9TYPE7gkvZXdgOvbfSaByJbCmfXmV
       depends_on:
         - postgresql
       networks:
         - clgportal-network

networks:
  clgportal-network:
    driver: bridge